"use client";

import { useEffect, useState, useCallback } from "react";
import SignalCard from "@/components/SignalCard";
import TradeDrawer from "@/components/TradeDrawer";
import PermissionGuard from "@/components/auth/permission_guard";
import { getTradingSignals } from "@/lib/api";
import { Button, PageHeader } from "@ds/components/ui";

export default function SignalsPage() {
  const [signals, setSignals] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [error, setError] = useState("");
  const [offset, setOffset] = useState(0);
  const [selectedSignal, setSelectedSignal] = useState<any>(null);

  const LIMIT = 50;

  const load = useCallback(async (off: number) => {
    try {
      const res = await getTradingSignals(`?limit=${LIMIT}&offset=${off}`);
      setSignals(res.items || []);
      setTotal(res.total);
    } catch (e) {
      setError((e as Error).message);
    }
  }, []);

  useEffect(() => { load(offset); }, [load, offset]);

  return (
    <PermissionGuard permission="trades.read">
      <div>
        <PageHeader
          title="Signals & ICT Setups"
          subtitle="Pending signals generated by the SMC / ICT engine"
          actions={<Button onClick={() => load(offset)}>Refresh</Button>}
        />

        {error && <div className="text-danger text-sm mb-3">{error}</div>}

        {signals.length === 0 && !error && (
          <div className="text-center py-8 text-ink-muted text-sm">No pending signals</div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {signals.map((s) => (
            <SignalCard key={s.id} signal={s} selected={selectedSignal?.id === s.id} onSelect={(id) => {
              const sig = signals.find((x) => x.id === id);
              if (sig) setSelectedSignal(sig);
            }} />
          ))}
        </div>

        {total > LIMIT && (
          <div className="flex items-center justify-between mt-4 text-sm text-ink-muted">
            <span>{total} total</span>
            <div className="flex gap-2">
              <Button variant="secondary" size="sm" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - LIMIT))}>Previous</Button>
              <Button variant="secondary" size="sm" disabled={offset + LIMIT >= total} onClick={() => setOffset(offset + LIMIT)}>Next</Button>
            </div>
          </div>
        )}

        <TradeDrawer trade={selectedSignal} onClose={() => setSelectedSignal(null)} />
      </div>
    </PermissionGuard>
  );
}
