# event_types.py
from enum import Enum


class EventType(str, Enum):
    BOT_STARTED = "BOT_STARTED"
    BOT_STOPPED = "BOT_STOPPED"

    TRADE_CREATED = "TRADE_CREATED"
    TRADE_OPENED = "TRADE_OPENED"
    TRADE_UPDATED = "TRADE_UPDATED"
    TRADE_CLOSED = "TRADE_CLOSED"
    TRADE_CANCELLED = "TRADE_CANCELLED"
    TRADE_BLOCKED = "TRADE_BLOCKED"

    BREAK_EVEN_MOVED = "BREAK_EVEN_MOVED"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    TRAILING_STOP_UPDATED = "TRAILING_STOP_UPDATED"

    TP_HIT = "TP_HIT"
    SL_HIT = "SL_HIT"

    NEWS_UPDATED = "NEWS_UPDATED"
    NEWS_COUNTDOWN = "NEWS_COUNTDOWN"
    FUNDAMENTAL_STATE_UPDATED = "FUNDAMENTAL_STATE_UPDATED"

    LICENSE_ACTIVATED = "LICENSE_ACTIVATED"
    LICENSE_EXPIRED = "LICENSE_EXPIRED"
    LICENSE_WARNING = "LICENSE_WARNING"

    ACCOUNT_CONNECTED = "ACCOUNT_CONNECTED"
    ACCOUNT_DISCONNECTED = "ACCOUNT_DISCONNECTED"
    ACCOUNT_RECONNECTED = "ACCOUNT_RECONNECTED"

    SCANNER_STARTED = "SCANNER_STARTED"
    SCANNER_STOPPED = "SCANNER_STOPPED"

    ENGINE_STARTED = "ENGINE_STARTED"
    ENGINE_STOPPED = "ENGINE_STOPPED"
    ENGINE_PAUSED = "ENGINE_PAUSED"
    ENGINE_RESUMED = "ENGINE_RESUMED"
    ENGINE_ERROR = "ENGINE_ERROR"

    ORDER_SENT = "ORDER_SENT"

    SETUP_DETECTED = "SETUP_DETECTED"
    CANDIDATE_FOUND = "CANDIDATE_FOUND"
    NO_SETUP = "NO_SETUP"
    PAPER_TRADE_PLANNED = "PAPER_TRADE_PLANNED"
    PAPER_TRADE_REJECTED = "PAPER_TRADE_REJECTED"
    PAPER_TRADE_FILLED = "PAPER_TRADE_FILLED"
    PAPER_TRADE_TP_HIT = "PAPER_TRADE_TP_HIT"
    PAPER_TRADE_SL_HIT = "PAPER_TRADE_SL_HIT"

    RISK_BREACH = "RISK_BREACH"
    RISK_CHECK = "RISK_CHECK"

    # ── Economic Calendar events ────────────────────────────────
    CALENDAR_UPDATED = "CALENDAR_UPDATED"
    ECONOMIC_EVENT_CREATED = "ECONOMIC_EVENT_CREATED"
    ECONOMIC_EVENT_UPDATED = "ECONOMIC_EVENT_UPDATED"
    ECONOMIC_EVENT_RELEASED = "ECONOMIC_EVENT_RELEASED"
    CALENDAR_T60_ALERT = "CALENDAR_T60_ALERT"
    CALENDAR_T30_ALERT = "CALENDAR_T30_ALERT"
    CALENDAR_T5_ALERT = "CALENDAR_T5_ALERT"
    CALENDAR_WEEKLY_SUMMARY = "CALENDAR_WEEKLY_SUMMARY"
    CALENDAR_DATA_UNAVAILABLE = "CALENDAR_DATA_UNAVAILABLE"

    ERROR = "ERROR"
    HEALTH_WARNING = "HEALTH_WARNING"
    HEALTH_OK = "HEALTH_OK"
    HEALTH_STATUS_CHANGE = "HEALTH_STATUS_CHANGE"
    SYSTEM_INFO = "SYSTEM_INFO"
    SYSTEM_ERROR = "SYSTEM_ERROR"


# Severity mapping for audit logs
EVENT_SEVERITY = {
    EventType.BOT_STARTED: "INFO",
    EventType.BOT_STOPPED: "INFO",
    EventType.TRADE_CREATED: "INFO",
    EventType.TRADE_OPENED: "INFO",
    EventType.TRADE_UPDATED: "INFO",
    EventType.TRADE_CLOSED: "INFO",
    EventType.TRADE_CANCELLED: "INFO",
    EventType.TRADE_BLOCKED: "WARN",
    EventType.BREAK_EVEN_MOVED: "INFO",
    EventType.PARTIAL_CLOSE: "INFO",
    EventType.TRAILING_STOP_UPDATED: "INFO",
    EventType.TP_HIT: "INFO",
    EventType.SL_HIT: "HIGH",
    EventType.NEWS_UPDATED: "INFO",
    EventType.NEWS_COUNTDOWN: "WARN",
    EventType.FUNDAMENTAL_STATE_UPDATED: "INFO",
    EventType.LICENSE_ACTIVATED: "INFO",
    EventType.LICENSE_EXPIRED: "HIGH",
    EventType.LICENSE_WARNING: "WARN",
    EventType.ACCOUNT_CONNECTED: "INFO",
    EventType.ACCOUNT_DISCONNECTED: "WARN",
    EventType.ACCOUNT_RECONNECTED: "INFO",
    EventType.SCANNER_STARTED: "INFO",
    EventType.SCANNER_STOPPED: "INFO",
    EventType.ENGINE_STARTED: "INFO",
    EventType.ENGINE_STOPPED: "INFO",
    EventType.ENGINE_PAUSED: "WARN",
    EventType.ENGINE_RESUMED: "INFO",
    EventType.ENGINE_ERROR: "HIGH",
    EventType.ORDER_SENT: "INFO",
    EventType.SETUP_DETECTED: "INFO",
    EventType.CANDIDATE_FOUND: "INFO",
    EventType.NO_SETUP: "DEBUG",
    EventType.PAPER_TRADE_PLANNED: "INFO",
    EventType.PAPER_TRADE_REJECTED: "INFO",
    EventType.PAPER_TRADE_FILLED: "INFO",
    EventType.PAPER_TRADE_TP_HIT: "INFO",
    EventType.PAPER_TRADE_SL_HIT: "WARN",
    EventType.RISK_BREACH: "CRITICAL",
    EventType.RISK_CHECK: "DEBUG",
    # Calendar events
    EventType.CALENDAR_UPDATED: "INFO",
    EventType.ECONOMIC_EVENT_CREATED: "INFO",
    EventType.ECONOMIC_EVENT_UPDATED: "INFO",
    EventType.ECONOMIC_EVENT_RELEASED: "INFO",
    EventType.CALENDAR_T60_ALERT: "WARN",
    EventType.CALENDAR_T30_ALERT: "WARN",
    EventType.CALENDAR_T5_ALERT: "HIGH",
    EventType.CALENDAR_WEEKLY_SUMMARY: "INFO",
    EventType.CALENDAR_DATA_UNAVAILABLE: "HIGH",
    # Errors / system
    EventType.ERROR: "ERROR",
    EventType.HEALTH_WARNING: "WARN",
    EventType.HEALTH_OK: "INFO",
    EventType.HEALTH_STATUS_CHANGE: "WARN",
    EventType.SYSTEM_INFO: "INFO",
    EventType.SYSTEM_ERROR: "CRITICAL",
}