class Callback:
    # Language
    LANG_AR = "LANG_AR"
    LANG_EN = "LANG_EN"
    LANG_FR = "LANG_FR"
    LANG_ES = "LANG_ES"

    # Onboarding (wizard)
    PERSONAL = "PERSONAL"
    FUNDED = "FUNDED"
    CHALLENGE = "CHALLENGE"
    OTHER_BROKER = "OTHER_BROKER"
    OTHER_PROP = "OTHER_PROP"
    ACCEPT_TERMS = "ACCEPT_TERMS"
    DECLINE_TERMS = "DECLINE_TERMS"
    CONTINUE = "CONTINUE"
    BACK = "BACK"

    # Trading Modes (wizard)
    MODE_ULTRA = "MODE_ULTRA"
    MODE_CONSERVATIVE = "MODE_CONSERVATIVE"
    MODE_BALANCED = "MODE_BALANCED"
    MODE_AGGRESSIVE = "MODE_AGGRESSIVE"

    # Main Menu
    MENU_MAIN = "MENU:MAIN"
    MENU_ACCOUNTS = "MENU:ACCOUNTS"
    MENU_ACTIVE = "MENU:ACTIVE"
    MENU_STATUS = "MENU:STATUS"
    MENU_PERFORMANCE = "MENU:PERFORMANCE"
    MENU_SETTINGS = "MENU:SETTINGS"
    MENU_LICENSE = "MENU:LICENSE"
    MENU_SUPPORT = "MENU:SUPPORT"
    MENU_LANGUAGE = "MENU:LANGUAGE"
    MENU_DASHBOARD = "MENU:DASHBOARD"
    ADD_ACCOUNT = "ADD_ACCOUNT"

    # Account actions
    ACCOUNT_OPEN = "ACCOUNT:OPEN"
    ACCOUNT_PAUSE = "ACCOUNT:PAUSE"
    ACCOUNT_RESUME = "ACCOUNT:RESUME"
    ACCOUNT_RESTART = "ACCOUNT:RESTART"
    ACCOUNT_START = "ACCOUNT:START"
    ACCOUNT_RESCAN = "ACCOUNT:RESCAN"
    ACCOUNT_RENAME = "ACCOUNT:RENAME"
    ACCOUNT_REMOVE = "ACCOUNT:REMOVE"
    ACCOUNT_REMOVE_CONFIRM = "ACCOUNT:REMOVE_CONFIRM"
    ACCOUNT_REMOVE_CANCEL = "ACCOUNT:REMOVE_CANCEL"

    # Navigation
    NAV_BACK = "NAV:BACK"

    # Activation
    ACTIVATE_BOT = "ACTIVATE_BOT"
    ENTER_LICENSE_KEY = "ENTER_LICENSE_KEY"
    CONFIRM_SETUP = "CONFIRM_SETUP"
    EDIT_SETUP = "EDIT_SETUP"

    # Connection Retry
    RETRY_CONNECTION = "RETRY_CONNECTION"
    RESTART_SETUP = "RESTART_SETUP"

    # Support / Tickets
    TICKET_CREATE = "TICKET:CREATE"
    TICKET_LIST = "TICKET:LIST"
    TICKET_VIEW = "TICKET:VIEW:"        # TICKET:VIEW:{ticket_id}
    TICKET_REPLY = "TICKET:REPLY:"      # TICKET:REPLY:{ticket_id}
    TICKET_STATUS = "TICKET:STATUS:"    # TICKET:STATUS:{status}
