"""add_symbol_mapping_to_account

Revision ID: 078c160ca56a
Revises: bd60416d05a8
Create Date: 2026-07-11 01:27:59.063733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '078c160ca56a'
down_revision: Union[str, Sequence[str], None] = 'bd60416d05a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_accounts', sa.Column('symbol_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('trading_accounts', 'real_trading_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_accounts', 'real_trading_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('trading_accounts', 'symbol_mapping')
    # ### end Alembic commands ###
