"""add_account_fingerprint_and_removed_at

Revision ID: 5599d4f834a7
Revises: 078c160ca56a
Create Date: 2026-07-12 14:35:06.228330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5599d4f834a7'
down_revision: Union[str, Sequence[str], None] = '078c160ca56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. add as nullable first (existing rows have null)
    op.add_column('trading_accounts', sa.Column('account_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('trading_accounts', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))

    # 2. backfill existing rows with a fingerprint based on platform|server|login
    op.execute(
        sa.text(
            "UPDATE trading_accounts "
            "SET account_fingerprint = encode(sha256(("
            "  COALESCE(upper(platform), '') || '|' || "
            "  COALESCE(replace(upper(server), ' ', ''), '') || '|' || "
            "  COALESCE(login::text, '')"
            ")::bytea), 'hex') "
            "WHERE account_fingerprint IS NULL"
        )
    )

    # 3. deduplicate — keep the newest active row per fingerprint, soft-remove older ones
    op.execute(
        sa.text(
            "UPDATE trading_accounts t "
            "SET removed_at = NOW(), "
            "    engine_status = 'REMOVED', "
            "    active = false, "
            "    verified = false "
            "WHERE t.id IN ("
            "  SELECT t2.id FROM ("
            "    SELECT id, ROW_NUMBER() OVER ("
            "      PARTITION BY account_fingerprint "
            "      ORDER BY created_at DESC"
            "    ) AS rn "
            "    FROM trading_accounts "
            "  ) t2 "
            "  WHERE t2.rn > 1"
            ")"
        )
    )

    # 4. now make it NOT NULL
    op.alter_column('trading_accounts', 'account_fingerprint', nullable=False)
    op.create_index(op.f('ix_trading_accounts_account_fingerprint'), 'trading_accounts', ['account_fingerprint'], unique=False)
    op.create_index('uq_active_mt_account_fingerprint', 'trading_accounts', ['account_fingerprint'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_mt_account_fingerprint', table_name='trading_accounts', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_trading_accounts_account_fingerprint'), table_name='trading_accounts')
    op.drop_column('trading_accounts', 'removed_at')
    op.drop_column('trading_accounts', 'account_fingerprint')
    # ### end Alembic commands ###
