"""add_license_id_engine_status

Revision ID: 8207de929a7e
Revises: 2bac382e7c09
Create Date: 2026-07-08 16:29:48.790241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8207de929a7e'
down_revision: Union[str, Sequence[str], None] = '2bac382e7c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_accounts', sa.Column('license_id', sa.String(length=36), nullable=True))
    op.add_column('trading_accounts', sa.Column('engine_status', sa.String(length=20), nullable=False, server_default='WAITING_ACTIVATION'))
    op.create_foreign_key(None, 'trading_accounts', 'licenses', ['license_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trading_accounts', type_='foreignkey')
    op.drop_column('trading_accounts', 'engine_status')
    op.drop_column('trading_accounts', 'license_id')
    # ### end Alembic commands ###
