"""initial

Revision ID: 9040ab378cde
Revises: 
Create Date: 2026-07-08 15:40:08.060173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9040ab378cde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('telegram_username', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('license_key', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_accounts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trading_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('broker', sa.String(length=120), nullable=True),
    sa.Column('prop_firm', sa.String(length=120), nullable=True),
    sa.Column('program', sa.String(length=120), nullable=True),
    sa.Column('program_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('server', sa.String(length=120), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('account_size', sa.Float(), nullable=True),
    sa.Column('demo_real', sa.String(length=10), nullable=True),
    sa.Column('trade_mode', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('leverage', sa.String(length=20), nullable=True),
    sa.Column('balance_snapshot', sa.Float(), nullable=True),
    sa.Column('equity_snapshot', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('broker_detected', sa.String(length=120), nullable=True),
    sa.Column('balance_detected', sa.Float(), nullable=True),
    sa.Column('equity_detected', sa.Float(), nullable=True),
    sa.Column('leverage_detected', sa.String(length=20), nullable=True),
    sa.Column('symbols_detected', sa.Text(), nullable=True),
    sa.Column('mismatches', sa.Text(), nullable=True),
    sa.Column('build', sa.Integer(), nullable=True),
    sa.Column('timezone_detected', sa.String(length=50), nullable=True),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('daily_loss', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('profit_target', sa.Float(), nullable=True),
    sa.Column('max_risk_trade', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_profiles')
    op.drop_table('account_scans')
    op.drop_table('trading_accounts')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_table('users')
    # ### end Alembic commands ###
