"""add_license_telegram_binding

Revision ID: bd60416d05a8
Revises: 8207de929a7e
Create Date: 2026-07-08 18:08:19.437219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd60416d05a8'
down_revision: Union[str, Sequence[str], None] = '8207de929a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('licenses', sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('licenses', sa.Column('bound_account_id', sa.String(length=36), nullable=True))
    op.add_column('licenses', sa.Column('transfer_locked', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'transfer_locked')
    op.drop_column('licenses', 'bound_account_id')
    op.drop_column('licenses', 'bound_at')
    op.drop_column('licenses', 'telegram_id')
    # ### end Alembic commands ###
